source "https://rubygems.org"

gemspec

# Exclude development-only gems from dependabot.
unless ENV["DEPENDABOT"]
  gem "rackup"
  gem "climate_control"
  gem "puma"
  gem "nokogiri"
  gem "dotenv"
  gem "capybara"
  gem "cuprite"
  gem "super_settings", ">= 2.5.0"

  gem "rake"
  gem "rspec", "~> 3.11"

  # Exclude development-only gems from the gemfiles generated by appraisal.
  unless defined?(::Appraisal::Gemfile) && is_a?(::Appraisal::Gemfile)
    gem "appraisal", require: false
    gem "standard", require: false
    gem "simplecov", require: false
    gem "yard", require: false
  end
end
